baseURL = "https://martinsautosalesar.com/"
languageCode = "en-us"
title = "Martin's Auto Sales | Quality Used Vehicles"
enableRobotsTXT = true
[taxonomies]
  category = "categories"
[related]
 includeNewer= true
[[related.indices]]
 name ="categories"
 weight = 100
