backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "vehicles" # Used in routes, e.g., /admin/collections/blog
    label: "Vehicle" # Used in the UI
    folder: "/content/vehicles-for-sale" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index"
    media_folder: "images"
    public_folder: "images"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Trim Level", name: "trim-level", widget: "string"}
      - {label: "Mileage", name: "mileage", widget: "number"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImg", widget: "image"}
      - {label: "Image Alt Text", name: "imgAlt", widget: "text"}
      - {label: "Category", name: "categories", widget: "select", options: ["trucks", "SUVs", "cars"]}
      - {label: "Status", name: "status", widget: "select", options: ["Coming Soon", "Available", "Sold"]}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "VIN", name: "vin", widget: "text"}
      - {label: "MSRP", name: "msrp", widget: "number"}
      - {label: "Features", name: "features", widget: "list", field: {label: "feature", name: "Feature", widget: "text"}}
      - {label: "Key Points", name: "keyPoints", widget: "list", field: {label: "feature", name: "Feature", widget: "text"}}
      - {label: "Gallery Images", name: "galleryImages", widget: "list", field: {label: "Image", name: "galleryImage", widget: "image"}}
  - name: "update"
    label: "Update"
    folder: /content/updates
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Display", name: "display", widget: "select", options: ["visible", "hidden"]}
      - {label: "Title", name: "title", widget: "hidden", default: "updates"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImg", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
